#pragma once

#define EE_HANDS

#define OLED_BRIGHTNESS 32
#define OLED_TIMEOUT 1000
#define OLED_UPDATE_INTERVAL 100
#define OLED_DISPLAY_ADDRESS 0x3C

#define ANALOG_JOYSTICK_X_AXIS_PIN F5
#define ANALOG_JOYSTICK_Y_AXIS_PIN F4
#define ANALOG_JOYSTICK_CLICK_PIN F6
//#define ANALOG_JOYSTICK_SPEED_MAX 2
//#define ANALOG_JOYSTICK_SPEED_REGULATOR 20

//#define POINTING_DEVICE_INVERT_X yes
//#define POINTING_DEVICE_INVERT_Y yes
