MCU = atmega32u4
F_CPU = 16000000
ARCH = AVR8
F_USB = $(F_CPU)
OPT_DEFS += -DINTERRUPT_CONTROL_ENDPOINT

# OLED
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = analog_joystick

SPLIT_POINTING_ENABLE = yes
POINTING_DEVICE_LEFT = yes
